name: build-test
on:
  workflow_dispatch: {}
  schedule:
    - cron: 15 */12 * * *
jobs:
  smoke:
    name: smoke
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: apache/tinkerpop
          ref: master
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: temurin
      - name: Build with Maven
        run: mvn clean install -DskipTests -Dci --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - devzero-ubuntu-24.04
          - devzero-ubuntu-24.04-lab
          - devzero-ubuntu-24.04-lab-kata-overlayfs
          - devzero-ubuntu-24.04-sysbox
          - self-hosted-vm
  cache-gremlin-server-docker-image:
    name: cache gremlin-server docker image
    timeout-minutes: 10
    needs: smoke
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: apache/tinkerpop
          ref: master
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: temurin
      - name: Generate Gremlin Server Base
        working-directory: .
        run: |
          mvn clean install -pl gremlin-server -DskipTests -DskipIntegrationTests=true -Dci -am
      - name: Save Docker image
        working-directory: ./gremlin-server
        run: docker save --output gremlin-server.tar tinkerpop/gremlin-server
      - uses: actions/cache@v4
        id: gremlin-server-test-docker-image
        with:
          path: |
            ./gremlin-server/*
            ~/.m2/repository/org/apache/tinkerpop/*
          key: ${{ github.sha }}
          # Disabled until Linux containers are supported on Windows runners: https://github.com/actions/virtual-environments/issues/252
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - devzero-ubuntu-24.04
          - devzero-ubuntu-24.04-lab
          - devzero-ubuntu-24.04-lab-kata-overlayfs
          - devzero-ubuntu-24.04-sysbox
          - self-hosted-vm
